# Generated by Django 3.2.4 on 2021-08-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img_notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('topUrlimg', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(blank=True, choices=[(1, '普通用户'), (2, 'VIP'), (3, 'SVIP')], null=True)),
                ('userName', models.CharField(max_length=10)),
                ('userPwd', models.CharField(max_length=100)),
                ('userTelphone', models.CharField(max_length=10)),
                ('userAddress', models.CharField(max_length=10)),
                ('userAge', models.CharField(max_length=4)),
                ('userImg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='usersImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userImg', models.ImageField(null=True, upload_to='static/user')),
            ],
        ),
        migrations.CreateModel(
            name='video_notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('topUrlimg', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo')),
            ],
        ),
    ]
